# Provides UTILS_SOURCES_DIR and UTILS_SOURCES variables

set(UTILS_SOURCES_DIR ${CMAKE_CURRENT_LIST_DIR})

set(UTILS_SOURCES 
    ${UTILS_SOURCES_DIR}/commandline.c
    ${UTILS_SOURCES_DIR}/commandline.h)

