# Provides PLATFORM_SOURCES and PLATFORM_INCLUDE_DIRS and PLATFORM_DEFINITIONS variables

set(PLATFORM_SOURCES_DIR ${CMAKE_CURRENT_LIST_DIR})
set(PLATFORM_SOURCES
    ${PLATFORM_SOURCES_DIR}/platform.c
    ${PLATFORM_SOURCES_DIR}/memtrace.c)

if(DTLS)
    include(${CMAKE_CURRENT_LIST_DIR}/tinydtls.cmake)
    set(PLATFORM_INCLUDE_DIRS ${PLATFORM_SOURCES_DIR} ${TINYDTLS_SOURCES_DIR})
    set(PLATFORM_SOURCES ${PLATFORM_SOURCES} ${TINYDTLS_SOURCES} ${PLATFORM_SOURCES_DIR}/dtlsconnection.c ${PLATFORM_SOURCES_DIR}/dtlsconnection.h)
    set(PLATFORM_INCLUDE_DIRS ${PLATFORM_SOURCES_DIR} ${TINYDTLS_SOURCES_DIR})
    set(PLATFORM_DEFINITIONS -DWITH_TINYDTLS)
else()
    set(PLATFORM_SOURCES ${PLATFORM_SOURCES} ${PLATFORM_SOURCES_DIR}/connection.c ${PLATFORM_SOURCES_DIR}/connection.h)
    set(PLATFORM_INCLUDE_DIRS ${PLATFORM_SOURCES_DIR})
endif()

