name: Build Documentation

on:
  pull_request:
    branches: [main]

jobs:
  documentation:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code including full history and submodules
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install dependencies from APT repository
      run:  |
        sudo apt-get update
        sudo apt-get install doxygen graphviz plantuml

    - name: Build Doxygen documentation
      run: tools/ci/run_ci.sh --run-doxygen

    - name: Upload Doxygen documentation
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: Doxygen documentation (HTML)
        path: build-wakaama/doxygen
