name: Build Documentation

on:
  pull_request:
    branches: [main]

jobs:
  documentation:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code including full history and submodules
      uses: actions/checkout@v4

    - name: Install dependencies from APT repository
      run:  |
        sudo apt-get update
        sudo apt-get install doxygen graphviz plantuml

    - name: Build Doxygen documentation
      run: tools/ci/run_ci.sh --run-doxygen

    - name: Upload Doxygen documentation
      uses: actions/upload-artifact@v4
      with:
        name: Doxygen documentation (HTML)
        path: build-wakaama/doxygen
