name: Documentation

on: [push, pull_request]

jobs:
  sphinx:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code including full history and submodules
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Install dependencies from APT repository
      run:  |
        sudo apt-get update
        sudo apt-get install cmake ninja-build


    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r doc/sphinx/requirements.txt

    - name: Build Sphinx documentation
      run: |
           sphinx-build -M html sphinx sphinx_output
      working-directory: doc/

    - name: Upload HTML documentation
      if: ${{ github.event_name == 'push' && github.ref == 'main' }}
      uses: actions/upload-artifact@v1
      with:
        name: Documentation (HTML)
        path: doc/sphinx_output/html
